#!/usr/bin/env bash
#
# setscript.sh — ONE-COMMAND CF developer onboarding (lives IN the CF repo — devs need no hub
# repo membership; the hub is public and is cloned read-only if missing).
#
# Creates `.env.cicd` at the CF repo root (gitignored — NEVER committed):
#   E2E_HUB_PATH          → a local starlabs-e2e-tests checkout (the Playwright loop-guard the
#                           predeploy gate runs lives there). Offers to clone it if absent.
#   CONSOLE_INGEST_TOKEN  → tried in order: ① GitHub Actions VARIABLE on this (private) repo via
#                           `gh variable get` — the easy path, ② Secret Manager on starlabs-cicd
#                           via firebase CLI, ③ paste (ask the operator).
#   CONSOLE_INGEST_URL    → starlabs-cicd functions base (default).
#
# Run from the CF repo root:  bash scripts/cicd/setscript.sh
set -uo pipefail

CF_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." >/dev/null 2>&1 && pwd)"
HUB_REPO_URL="https://github.com/School-of-Excellence/starlabs-e2e-tests.git"

echo "══ CF CI/CD hooks setup (.env.cicd) ═══════════════════════════════"
echo "   CF repo: $CF_ROOT"

# ── 1. E2E_HUB_PATH — prompt; offer a fresh clone if the path doesn't hold the hub ─────────────
DEFAULT_HUB="$HOME/Documents/starlabs-e2e-tests"
read -r -p "E2E_HUB_PATH — your starlabs-e2e-tests checkout [${DEFAULT_HUB}]: " HUB_IN
HUB_PATH="${HUB_IN:-$DEFAULT_HUB}"
HUB_PATH="${HUB_PATH/#\~/$HOME}"

if [ ! -f "$HUB_PATH/scripts/cf-predeploy.sh" ]; then
  echo "   ⚠ no hub checkout at $HUB_PATH"
  read -r -p "   Clone it there now? (the hub repo is public, read-only is fine) [Y/n]: " CLONE
  if [ "${CLONE:-Y}" = "Y" ] || [ "${CLONE:-y}" = "y" ]; then
    git clone "$HUB_REPO_URL" "$HUB_PATH" || { echo "🛑 clone failed" >&2; exit 1; }
    echo "   ✓ cloned. NOTE: run (cd $HUB_PATH && npm ci && ./setup.sh) before your first deploy —"
    echo "     the gate needs the hub's node_modules + emulator config."
  else
    echo "🛑 the predeploy gate cannot run without a hub checkout — aborting (nothing written)." >&2
    exit 1
  fi
fi

# ── 2. Token — gh variable (this repo) → Secret Manager → paste ────────────────────────────────
TOKEN=""
if command -v gh >/dev/null 2>&1; then
  echo "   trying GitHub Actions variable CONSOLE_INGEST_TOKEN on this repo (gh CLI)…"
  TOKEN="$(gh variable get CONSOLE_INGEST_TOKEN --repo School-of-Excellence/starlabs-cloud-function 2>/dev/null | tr -d '[:space:]' || true)"
fi
if [ -z "$TOKEN" ] && command -v firebase >/dev/null 2>&1; then
  echo "   trying Secret Manager on starlabs-cicd (firebase CLI)…"
  TOKEN="$(firebase functions:secrets:access CONSOLE_INGEST_TOKEN --project starlabs-cicd 2>/dev/null | tail -1 | tr -d '[:space:]' || true)"
fi
if [ -z "$TOKEN" ]; then
  echo "   ⚠ could not fetch the token automatically."
  read -r -s -p "   Paste CONSOLE_INGEST_TOKEN (ask the operator): " TOKEN
  echo ""
fi
if [ -z "$TOKEN" ]; then
  echo "🛑 no token — aborting (nothing written)." >&2
  exit 1
fi

# ── 3. Write .env.cicd ─────────────────────────────────────────────────────────────────────────
ENV_FILE="$CF_ROOT/.env.cicd"
cat > "$ENV_FILE" <<EOF
# Generated by scripts/cicd/setscript.sh — DO NOT COMMIT (gitignored).
E2E_HUB_PATH=$HUB_PATH
CONSOLE_INGEST_URL=https://us-central1-starlabs-cicd.cloudfunctions.net
CONSOLE_INGEST_TOKEN=$TOKEN
EOF
chmod 600 "$ENV_FILE"
echo "   ✓ wrote $ENV_FILE (mode 600)"

# ── 4. Readiness check — the predeploy gate needs a WORKING hub + CF deps ──────────────────────
warn=0
[ -d "$HUB_PATH/node_modules" ] || { echo "   ⚠ hub node_modules missing → (cd $HUB_PATH && npm ci)"; warn=1; }
[ -f "$HUB_PATH/firebase.emulator.json" ] || { echo "   ⚠ hub emulator config missing → run the hub's ./setup.sh once"; warn=1; }
[ -d "$CF_ROOT/functions/node_modules" ] || { echo "   ⚠ functions/node_modules missing → (cd functions && npm ci)"; warn=1; }
if [ "$warn" = "0" ]; then
  echo "── ✅ ready: firebase deploy now runs the loop-guard gate + reports to the console"
else
  echo "── ⚠ .env.cicd written, but fix the warnings above BEFORE your first deploy"
fi
